version: '3.7'

services:
  flask-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-service
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    ports:
      - "5050:5050"
    depends_on:
      - prometheus
      - exporter

  prometheus:
    image: prom/prometheus:v2.25.2
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  exporter:
    image: prom/node-exporter:v1.2.2
    container_name: exporter
    restart: unless-stopped
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
    links:
      - prometheus
    restart: unless-stopped
