global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'flask-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask-service:5050']
  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'exporter:9100' ]
